# Auto-labeling configuration for Pull Requests
# Based on file paths changed in the PR
# See: https://github.com/actions/labeler
# Note: actions/labeler only supports file path patterns, not PR body matching

# Bug fix labels - matches files with fix/bug/error in name
fix:
  - '**/*fix*'
  - '**/*bug*'
  - '**/*error*'

# Documentation labels - matches markdown files and docs directories
docs:
  - '**/*.md'
  - 'docs/**'
  - 'documentation/**'

# Test labels - matches test files and directories
test:
  - '**/__tests__/**'
  - '**/*.test.*'
  - '**/*.spec.*'
  - '**/test/**'

# Chore/maintenance labels - matches config files and dependency files
chore:
  - '.github/**'
  - '**/package.json'
  - '**/package-lock.json'
  - '**/go.mod'
  - '**/go.sum'
  - '**/.gitignore'
  - '**/.editorconfig'

# CI/CD labels - matches workflow files
ci:
  - '.github/workflows/**'
  - '.github/actions/**'

# Build system labels - matches build-related files
build:
  - '**/Dockerfile*'
  - '**/docker-compose*'
  - '**/Makefile'
  - '**/build.*'
  - '**/CMakeLists.txt'

# Style/formatting labels - matches formatting config files
style:
  - '**/.prettierrc*'
  - '**/.eslintrc*'
  - '**/prettier.config.*'
  - '**/eslint.config.*'

# Component-specific labels
formulus:
  - 'formulus/**'

formulus-formplayer:
  - 'formulus-formplayer/**'

synkronus:
  - 'synkronus/**'

synkronus-cli:
  - 'synkronus-cli/**'

# Dependencies labels - matches dependency files
dependencies:
  - '**/package.json'
  - '**/package-lock.json'
  - '**/go.mod'
  - '**/go.sum'
  - '**/yarn.lock'
  - '**/pnpm-lock.yaml'

