const StyleDictionary = require('style-dictionary');

// Custom header function
const customHeader = () => {
  return `/**
 * ODE Design Tokens
 * 
 * This file is auto-generated by Style Dictionary.
 * Do not edit directly. Edit source files in src/tokens/ instead.
 * 
 * Generated: ${new Date().toISOString()}
 */
`;
};

// Register custom format
StyleDictionary.registerFormat({
  name: 'customHeader',
  formatter: customHeader
});

// Load and export the config
module.exports = require('./config.json');

