const StyleDictionary = require('style-dictionary');

// Custom header function - must return array of strings
const customHeader = () => {
  return [
    '/**',
    ' * ODE Design Tokens',
    ' *',
    ' * This file is auto-generated by Style Dictionary.',
    ' * Do not edit directly. Edit source files in src/tokens/ instead.',
    ' *',
    ` * Generated: ${new Date().toISOString()}`,
    ' */',
    ''
  ];
};

// Register custom fileHeader
StyleDictionary.registerFileHeader({
  name: 'customHeader',
  fileHeader: customHeader
});

// Load config
const config = require('./config.json');

// Export the config
module.exports = config;

