module.exports = function() {
  return `/**
 * ODE Design Tokens
 * 
 * This file is auto-generated by Style Dictionary.
 * Do not edit directly. Edit source files in src/tokens/ instead.
 * 
 * Generated: ${new Date().toISOString()}
 */
`;
};

